version: '3.8'

services:
  admin-panel:
    build: .
    container_name: vpn-admin-panel
    ports:
      - "5000:5000"
    environment:
      - SECRET_KEY=${SECRET_KEY:-your_secret_key_here}
      - DEBUG=${DEBUG:-False}
      - PORT=5000
      - XRAY_PANEL_URL=${XRAY_PANEL_URL:-http://74.81.55.39:8001}
      - XRAY_ADMIN_EMAIL=${XRAY_ADMIN_EMAIL:-admin@vpnvietnam.com}
      - XRAY_ADMIN_PASSWORD=${XRAY_ADMIN_PASSWORD:-Vpnvietnam123@!}
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    networks:
      - vpn-network

networks:
  vpn-network:
    driver: bridge
